"""Task-scoped runtimes: display selection never participates in execution."""

import asyncio
from contextlib import AsyncExitStack
from functools import partial

from agent_platform.adapters.sqlite.jev_tasks import SqliteJevTaskStore
from agent_platform.bootstrap import build_application_services
from agent_platform.bootstrap_futures import assemble_multiscale_context
from agent_platform.domain.agent_controls import ControlSelection
from agent_platform.domain.sessions import TradingStyle
from agent_platform.ports.futures_market import FuturesMarketUnavailable
from agent_platform.ports.sessions import RevisionConflict


class JevTaskWorkbench:
    def __init__(self, root, config, services, *, factory=build_application_services):
        self.root = root.resolve()
        self.config, self.base = config, services
        self.factory = (
            partial(factory, clock=services.sessions.clock)
            if services is not None and factory is build_application_services
            else factory
        )  # Task wallets share the root UTC proof and one calibration worker.
        self.store = SqliteJevTaskStore(self.root)
        self.folder = self.root.parent / (self.root.stem + "-tasks")
        self.contexts = {}
        self.stack = AsyncExitStack()
        self.lock = asyncio.Lock()

    def interval(self, row):
        if row.decision_interval_seconds is not None:
            return row.decision_interval_seconds
        return (
            row.selection.decision_interval_seconds
            if row.selection
            else self.config.futures_cadence.decision_seconds
        )

    def task_config(self, row=None):
        changes = {"jev_workbench": False, "futures_task_only": True}
        if row is not None:
            changes["futures_multiscale"] = self.input_mode(row) == "multiscale"
            changes["futures_cadence"] = self.config.futures_cadence.model_copy(
                update={"decision_seconds": self.interval(row)}
            )
        if not self.config.paper_mock:
            # All tasks share the ORIGINAL cumulative ledger, including unknown reservations.
            changes["model_budget_database"] = self.config.model_budget_database or self.root
        return self.config.model_copy(update=changes)

    @staticmethod
    def input_mode(row):
        return row.context_mode or (row.selection.context_mode if row.selection else "legacy")

    async def open(self):
        await self.store.initialize()
        await self.store.import_legacy()
        self.folder.mkdir(parents=True, exist_ok=True)
        try:
            for row in await self.store.all():
                if not row.legacy:
                    await self._services(row)
        except BaseException:
            await self.stack.aclose()
            raise
        return self

    async def shutdown(self):
        await self.stack.aclose()

    async def _services(self, row):
        if row.legacy:
            active = await self.base.sessions.store.active()
            if (
                row.decision_interval_seconds is not None
                and active
                and active.session_id == row.session_id
            ):
                self._apply_cadence(self.base.futures_trading, self.interval(row))
            if active and active.session_id == row.session_id and row.context_mode is not None:
                svc = self.base.futures_trading
                if (svc.multiscale is not None) != (self.input_mode(row) == "multiscale"):
                    async with svc.context_gate:
                        previous = svc.multiscale
                        svc.multiscale = (
                            await assemble_multiscale_context(
                                config=self.task_config(row),
                                stack=self.stack,
                                database_path=self.root,
                                clock=svc.clock,
                                model=svc.model,
                            )
                            if self.input_mode(row) == "multiscale"
                            else None
                        )
                        svc.context_epoch += 1
                        if previous is not None:
                            await previous.aclose()
            return self.base
        if row.task_id not in self.contexts:
            # The filename is generated by the server and indexed before it is opened.
            services = await self.stack.enter_async_context(
                self.factory(self.folder / (row.task_id + ".sqlite3"), self.task_config(row))
            )
            services.futures_trading.advisory_only = row.kind == "jev_advice"
            self.contexts[row.task_id] = services
        return self.contexts[row.task_id]

    @staticmethod
    def _apply_cadence(service, seconds):
        if service.cadence.decision_seconds == seconds:
            return
        service.cadence = service.cadence.model_copy(update={"decision_seconds": seconds})
        runtime = getattr(service, "cadence_runtime", None)
        if runtime is not None:
            runtime.set_decision_interval(seconds)

    async def update_cadence(self, task_id, selection):
        async with self.lock:
            row, services, session, account = await self._owned_unlocked(
                task_id, selection.session_revision, selection.expected_revision
            )
            if row.cadence_revision != selection.cadence_revision:
                raise RevisionConflict("cadence changed")
            if account and account.status in ("running", "liquidated"):
                raise ValueError("cadence_requires_paused")
            if self.interval(row) != selection.decision_interval_seconds:
                row = row.model_copy(
                    update={
                        "decision_interval_seconds": selection.decision_interval_seconds,
                        "cadence_revision": row.cadence_revision + 1,
                    }
                )
                await self.store.save(row)
                self._apply_cadence(services.futures_trading, selection.decision_interval_seconds)
            return await self._view(row, services, session)

    async def update_context(self, task_id, selection):
        async with self.lock:
            row, services, session, account = await self._owned_unlocked(
                task_id, selection.session_revision, selection.expected_revision
            )
            if row.context_revision != selection.context_revision:
                raise RevisionConflict("input mode changed")
            if account and account.status in ("running", "liquidated"):
                raise ValueError("context_requires_paused")
            if self.input_mode(row) == selection.context_mode:
                return await self._view(row, services, session)
            svc = services.futures_trading
            staged = AsyncExitStack()
            try:
                context = None
                if selection.context_mode == "multiscale":
                    context = await assemble_multiscale_context(
                        config=self.task_config(row),
                        stack=staged,
                        database_path=self.root
                        if row.legacy
                        else self.folder / (task_id + ".sqlite3"),
                        clock=svc.clock,
                        model=svc.model,
                    )
                # Serialize input preparation/cleanup and funds state. A result
                # from before pause cannot pass the wallet's revision guard.
                async with svc.context_gate:
                    async with svc.gate:
                        _, _, session, account = await self._owned_unlocked(
                            task_id, selection.session_revision, selection.expected_revision
                        )
                        if account and account.status in ("running", "liquidated"):
                            raise ValueError("context_requires_paused")
                        updated = row.model_copy(
                            update={
                                "context_mode": selection.context_mode,
                                "context_revision": row.context_revision + 1,
                            }
                        )
                        await self.store.save(updated)
                        previous, svc.multiscale = svc.multiscale, context
                        svc.context_epoch += 1
                        self.stack.push_async_callback(staged.pop_all().aclose)
                    if previous is not None:
                        await previous.aclose()
            finally:
                await staged.aclose()
            return await self._view(updated, services, session)

    async def context(self, task_id):
        async with self.lock:
            # Read the interval revision under the same lock as updates. A
            # delayed legacy view must never reapply its older runtime interval.
            row = await self.store.get(task_id)
            services = await self._services(row)
        if row.session_id is None:
            session = await services.sessions.store.active()
        else:
            session = await services.sessions.store.get(row.session_id)
        return row, services, session

    async def create(self, selection):
        async with self.lock:
            row, fresh = await self.store.reserve(selection)
            services = await self._services(row)
            if row.setup == "creating":
                session = await services.sessions.store.active()
                if session is None:
                    session = await services.sessions.create(
                        TradingStyle(strength=selection.style_strength), selection.analysis_target
                    )
                if (
                    session.analysis_target != selection.analysis_target
                    or session.style.strength != selection.style_strength
                ):
                    raise ValueError("task session identity conflicts")
                row = row.model_copy(update={"session_id": session.session_id})
                await self.store.save(row)
                controls = await services.controls.current()
                await services.controls.update(
                    ControlSelection(
                        mode="auto",
                        execution_environment="paper",
                        trader_enabled=True,
                        jev_enabled=False,
                        confirmed=True,
                    ),
                    expected_revision=controls.revision,
                )
                # Commit setup before starting; a lost response/retry never restarts a paused task.
                row = row.model_copy(update={"setup": "ready"})
                await self.store.save(row)
                fresh = True
        if fresh:
            try:
                await self._configure(row, services)
                if selection.start:
                    view = await self.view(row.task_id)
                    await self.start(
                        row.task_id, view["session"]["revision"], view["account"]["revision"]
                    )
            except (ValueError, LookupError, TimeoutError, FuturesMarketUnavailable) as error:
                await self._failure(row, error)
        return await self.view(row.task_id)

    async def _failure(self, row, error):
        # Store only the bounded diagnostic, never provider text or credentials.
        codes = {
            "session_not_running",
            "source_changed",
            "run_unconfigured",
            "runtime_not_owned",
            "funding_publication_pending",
            "funding_catchup_pending",
            "execution_unresolved",
        }
        reason = (
            "market_unavailable"
            if isinstance(error, FuturesMarketUnavailable)
            else {
                "paper model trial expired or has not started": "model_policy_expired",
                "paper model is read-only": "model_read_only",
            }.get(str(error), str(error) if str(error) in codes else "configuration_unavailable")
        )
        latest = await self.store.get(row.task_id)
        await self.store.save(latest.model_copy(update={"failure": reason}))

    async def _configure(self, row, services):
        svc = services.futures_trading
        session = await services.sessions.store.get(row.session_id)
        if await svc.store.run(svc.scope(session).account_ref) is None:
            if row.selection is None:
                raise ValueError("legacy_configuration_required")
            await svc.configure(
                row.selection.limits,
                row.selection.policy,
                session_id=session.session_id,
                style_revision=session.style_revision,
            )

    async def start(self, task_id, session_revision, account_revision):
        async with self.lock:
            row, services, session, _ = await self._owned_unlocked(
                task_id, session_revision, account_revision
            )
            try:
                await self._configure(row, services)
                if session.status != "running":
                    session = await services.sessions.transition(
                        session.session_id, "running", session.revision
                    )
                svc = services.futures_trading
                account = await svc.backend.account(svc.scope(session), svc.clock.utcnow())
                controls = await services.controls.current()
                await svc.start(
                    account_ref=account.scope.account_ref,
                    expected_revision=account.revision,
                    style_revision=session.style_revision,
                    trader_revision=controls.trader_revision,
                )
                await self.store.save(row.model_copy(update={"failure": None}))
            except (ValueError, LookupError, TimeoutError, FuturesMarketUnavailable) as error:
                await self._failure(row, error)
                raise
        return await self.view(task_id)

    async def _owned_unlocked(self, task_id, session_revision, account_revision):
        # Contexts already exist for ready tasks; avoid acquiring the manager lock twice.
        row = await self.store.get(task_id)
        services = await self._services(row)
        session = await services.sessions.store.get(row.session_id) if row.session_id else None
        active = await services.sessions.store.active()
        if session is None or active is None or active.session_id != session.session_id:
            raise ValueError("session_closed")
        if session.revision != session_revision:
            raise RevisionConflict("session changed")
        svc = services.futures_trading
        run = await svc.store.run(svc.scope(session).account_ref)
        account = await svc.backend.account(svc.scope(session), svc.clock.utcnow()) if run else None
        if (account.revision if account else 0) != account_revision:
            raise RevisionConflict("account changed")
        return row, services, session, account

    async def pause(self, task_id, session_revision, account_revision, *, close=False):
        async with self.lock:
            row, services, session, account = await self._owned_unlocked(
                task_id, session_revision, account_revision
            )
            svc = services.futures_trading
            if close and account and account.quantity != 0:
                raise ValueError("close_requires_flat_position")
            if account and account.status == "running":
                await svc.pause(
                    account_ref=account.scope.account_ref, expected_revision=account.revision
                )
            status = "closed" if close else "paused"
            if session.status == "configured" and not close:
                return await self._view(row, services, session)
            if session.status != status:
                session = await services.sessions.transition(
                    session.session_id, status, session.revision
                )
            return await self._view(row, services, session)

    async def list(self):
        await self.store.import_legacy()
        rows = []
        for row in await self.store.all():
            _, services, session = await self.context(row.task_id)
            account = None
            usage = None
            if session:
                scope = services.futures_trading.scope(session)
                try:
                    account = await services.futures_trading.backend.account(
                        scope, services.futures_trading.clock.utcnow()
                    )
                except (ValueError, LookupError):
                    pass
                model = services.futures_trading.model
                if hasattr(model, "session_usage"):
                    usage = await model.session_usage(
                        session.session_id,
                        wallet_database=services.futures_trading.store.path,
                    )
            rows.append(
                {
                    **row.model_dump(mode="json", exclude={"selection"}),
                    "model_usage": usage,
                    "symbol": session.analysis_target.symbol
                    if session
                    else row.selection.analysis_target.symbol,
                    "status": "closed"
                    if session and session.status == "closed"
                    else account.status
                    if account
                    else "configured",
                }
            )
        svc = self.base.futures_trading
        budget = await svc.model.budget_status() if hasattr(svc.model, "budget_status") else None
        return {"tasks": rows, "model_budget": budget, "regular_agent": "planned"}

    async def view(self, task_id):
        row, services, session = await self.context(task_id)
        return await self._view(row, services, session)

    async def _view(self, row, services, session):
        svc = services.futures_trading
        active = await services.sessions.store.active()
        if session and active and session.session_id == active.session_id:
            view = await svc.public_view()
        else:
            view = {
                "account": None,
                "cycles": [],
                "operations": [],
                "quote": None,
                "paid_models_enabled": False,
                "archive_summary": None,
                "operation_mode": "advice" if row.kind == "jev_advice" else "auto_paper",
            }
            if session:
                scope = svc.scope(session)
                run = await svc.store.run(scope.account_ref)
                if run:
                    view["policy"] = run.policy.model_dump(mode="json")
                    view["limits"] = run.limits.model_dump(mode="json")
                    view["account"] = (
                        await svc.backend.account(scope, svc.clock.utcnow())
                    ).model_dump(mode="json")
                    view["cycles"] = [
                        c.public_summary() for c in await svc.store.recent(scope.account_ref)
                    ]
                    view["archive_summary"] = await svc.archive.summary(scope.account_ref)
        view["session"] = session.model_dump(mode="json") if session else None
        view["task"] = row.model_dump(mode="json", exclude={"selection"})
        view["task"]["cadence_revision"] = row.cadence_revision
        view["task"]["context_revision"] = row.context_revision
        view["context_mode"] = self.input_mode(row)
        view.setdefault("multiscale_context", None)
        view["cadence"] = svc.cadence.model_copy(
            update={"decision_seconds": self.interval(row)}
        ).model_dump(mode="json")
        view["readonly"] = session is None or session.status == "closed"
        view["style_strength"] = session.style.strength if session else row.selection.style_strength
        return view
