"""Durable event delivery; dispatched work must be reconciled before retry."""

from datetime import datetime
from typing import Protocol

from agent_platform.domain.agent_events import EventDelivery, EventLease, WatchEvent


class AgentEventStorePort(Protocol):
    async def claim(self, lane_id: str, now: datetime, lease_seconds: int) -> EventLease | None: ...
    async def renew(self, lease: EventLease, now: datetime, lease_seconds: int) -> EventLease: ...
    async def release(self, lease: EventLease, now: datetime) -> EventDelivery: ...
    async def complete(self, lease: EventLease, run_id: str, now: datetime) -> None: ...
    async def fail(
        self, lease: EventLease, reason: str, retryable: bool, now: datetime
    ) -> EventDelivery: ...
    async def get(self, event_id: str) -> WatchEvent: ...
    async def delivery(self, event_id: str) -> EventDelivery: ...
    async def recover(self, now: datetime) -> tuple[EventDelivery, ...]: ...
    async def mark_dispatched(self, lease: EventLease, run_id: str, now: datetime) -> None: ...
