"""Bounded auxiliary history without access to the permanent trading journal."""

from datetime import datetime
from pathlib import Path
from typing import Protocol

from agent_platform.domain.market_archive import MarketArchiveRecord, RetentionReport


class MarketArchivePort(Protocol):
    async def initialize(self) -> None: ...
    async def append_many(self, records: tuple[MarketArchiveRecord, ...]) -> tuple[bool, ...]: ...
    async def get(self, record_id: str) -> MarketArchiveRecord | None: ...
    async def pin(self, record_id: str, source_hash: str) -> None: ...
    async def prune(self, as_of: datetime, *, limit: int = 1000) -> RetentionReport: ...
    async def backup(self, destination: Path) -> None: ...
