from typing import Protocol

from agent_platform.domain.position_protection import PositionProtection
from agent_platform.domain.trade_intents import TradeIntent
from agent_platform.domain.trading_scope import ExecutionScope


class ProtectionStorePort(Protocol):
    async def prepare(self, intent: TradeIntent) -> PositionProtection: ...
    async def get(self, protection_id: str) -> PositionProtection: ...
    async def get_intent(self, intent_id: str) -> TradeIntent: ...
    async def save(
        self, protection: PositionProtection, expected_revision: int
    ) -> PositionProtection: ...
    async def recover(self, scope: ExecutionScope) -> tuple[PositionProtection, ...]: ...
