"""Lifecycle and maintenance stay outside the shared decision/execution application."""

from typing import Protocol

from agent_platform.domain.trading_execution import ExecutionScope
from agent_platform.domain.trading_runtime import FundingCheckpoint, TradingCycle, TradingRun


class TradingRuntimeStorePort(Protocol):
    async def configure(self, run: TradingRun) -> None: ...
    async def run(self, account_ref: str) -> TradingRun | None: ...
    async def checkpoint(self, account_ref: str) -> FundingCheckpoint | None: ...
    async def save_checkpoint(self, checkpoint: FundingCheckpoint) -> None: ...
    async def claim(self, cycle: TradingCycle) -> None: ...
    async def prepare(self, cycle: TradingCycle) -> None: ...
    async def finish(self, cycle: TradingCycle) -> None: ...
    async def recent(self, account_ref: str) -> tuple[TradingCycle, ...]: ...


class FuturesLifecyclePort(Protocol):
    async def configure(self, scope, limits, rules, at, *, style_revision): ...
    async def start(self, scope, revision, at, *, style_revision, trader_revision): ...
    async def pause(self, scope, revision, at): ...
    async def recover(self, at): ...
    async def maintenance_accounts(self) -> tuple[tuple[ExecutionScope, object], ...]: ...
    async def settle(self, scope, funding, at): ...
    async def mark(self, scope, quote, at): ...
    async def recent(self, scope): ...
