"""Watch persistence boundary; revisions are compare-and-swap tokens."""

from datetime import datetime
from typing import Protocol

from agent_platform.domain.watches import WatchDefinition, WatchEvaluation, WatchFrame, WatchRecord


class WatchStorePort(Protocol):
    async def create(self, definition: WatchDefinition) -> WatchRecord: ...
    async def replace(self, definition: WatchDefinition, expected_revision: int) -> WatchRecord: ...
    async def cancel(self, watch_id: str, expected_revision: int, at: datetime) -> WatchRecord: ...
    async def list_active(self, lane_id: str) -> tuple[WatchRecord, ...]: ...
    async def list_monitored(self, lane_id: str, now: datetime) -> tuple[WatchRecord, ...]: ...
    async def get(self, watch_id: str) -> WatchRecord: ...
    async def partition_healthy(self, watch_id: str) -> bool: ...
    async def commit_evaluation(
        self, watch_id: str, expected_revision: int, frame: WatchFrame, result: WatchEvaluation
    ) -> WatchRecord: ...
    async def expire(self, lane_id: str, now: datetime) -> tuple[WatchRecord, ...]: ...
